### ISSUE TITLE
Low Performance

### ISSUE THREAD

**Issue by dimiii** [kareez/dahgan#29]
Hi, I noted that performance degrades with increasing the size of a document. 

Here is a simple code, that generates a series of documents in the next format:

```yaml
---
- items:
   - name: A
     option: A
 # ... skip
   - name: A
     option: A
```
and then parses them:

```kotlin
fun main(args: Array<String>) {
    val docs = listOf(1, 2, 4, 8, 16, 32, 64).map {
        ("""
            ---
            - items:
         """ +
         """
              - name: A
                option: A
         """.repeat(it)).trimIndent()
    }

    docs.forEachIndexed { idx, doc ->
        val time = measureTimeMillis {
            loadAll(doc)
        }
        println("Case #$idx time: $time (ms)")
    }
}
```

Output:
```
Case #0 time: 409 (ms)
Case #1 time: 125 (ms)
Case #2 time: 144 (ms)
Case #3 time: 275 (ms)
Case #4 time: 1465 (ms)
Case #5 time: 6883 (ms)
Case #6 time: 52268 (ms)     
```

I think 50 seconds is an inappropriate time.

**Comment by kareez** [comment]
Thanks for the investigation. I'll have a look if there is something that can be improved.

**Comment by charleskorn** [comment]
I am also seeing similar issues - over five seconds to parse a 115 line YAML file.

**Comment by kareez** [comment]
Apparently, the issue is in Loader. the Tokenizer (Core module) performance is reasonable but Loader is definitely having a serious issue. 

From  [README](https://github.com/kareez/dahgan/blob/develop/loader/README.md#loader-module):
> The Loader module is an example to demonstrate how generated YEAST tokens from Core module can be used for further processes. It takes ...

According to README, the loader is just a sample code to show the usage of YEAST tokens. But anyway I'm going to spend some time to find the root cause and a potential solution. Any suggestion/help is really appreciated.

**Comment by charleskorn** [comment]
I am not using the loader (just the core module) and I'm seeing the performance issues I mentioned earlier.
